import { ConnectButton } from '@rainbow-me/rainbowkit';
import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import SwapCard from '../views/swap/SwapCard';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Demo</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>

      <main className={styles.main}>
        <ConnectButton />
        <div>
          <h2>Swap</h2>
          <SwapCard />
        </div>

      </main>

    </div>
  );
};

export default Home;
